name: Enviar para a VPS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Enviar os ficheiros via ssh para a vps
        uses: appleboy/scp-action@v0.1.4
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: david
          PORT: 22
          KEY: ${{ secrets.KEY }}
        with:
          source: "."
          target: "/home/david/assistentecraftsapiens"
  updateDani:
    name: Build and re-run Assistant 
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Iniciando o assistente
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: david
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            echo "Entrando no dir√©torio"
            cd assistentecraftsapiens

            echo "Desligando o processo anterior"
            docker stop assistentecraftsapiens
            docker rm assistentecraftsapiens
            sleep 3
            echo "Buildando o bot"
            docker build -t assistentecraftsapiens .
            sleep 2
            echo "Ligando AssistenteCraftSapiens"
            docker run -d --name=AssistenteCraftsapiens --memory=300m --memory-reservation=100m assistentecraftsapiens
